### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by iamyajat** [iamyajat/retro-portfolio-website#1]
Make the website responsive for various different screen sizes

**Comment by griseduardo** [comment]
Hello, I would like to work in this issue

**Comment by iamyajat** [comment]
@griseduardo sure

**Comment by VasekS** [comment]
Hi @iamyajat, is this issue still for grabs? I'm not seeing any pull requests and I can address this asap :)

**Comment by iamyajat** [comment]
Hey @VasekS, sorry, @griseduardo is working on this issue right now.
