### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by iamyajat** [iamyajat/retro-portfolio-website#2]
The following needs to be done:
1. Change title
2. Add a link to the website
3. Add some screenshots
4. Add instructions to run locally

**Comment by erikvegax** [comment]
i can pick this up!

**Comment by iamyajat** [comment]
go ahead @erikvega

**Comment by erikvegax** [comment]
when you say screenshots, do you mean of the project?

**Comment by iamyajat** [comment]
@erikvega yes. You can get them from https://retro-portfolio.pages.dev/.
