### ISSUE TITLE
Navbar hidden behind the URL bar on mobile

### ISSUE THREAD

**Issue by iamyajat** [iamyajat/retro-portfolio-website#5]
The navbar is hidden behind the URL bar on mobiles -

![image](https://user-images.githubusercontent.com/68477362/138638609-82a6b2a3-508c-487c-8f32-00e9361bf747.png)

It should be visible like this below the URL bar -

![image](https://user-images.githubusercontent.com/68477362/138638742-db22e99b-ec06-4543-afad-995ca814816e.png)

**Comment by VasekS** [comment]
Hi @iamyajat, please assign this to me :)

**Comment by iamyajat** [comment]
@VasekS sure

**Comment by oneamanish** [comment]
see my pull req.

**Comment by iamyajat** [comment]
Thanks for contributing, but the issue was already solved ✌🏼
